name: env_solara
channels:
  - terradue
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - loguru
  - ipyleaflet==0.17.3
  - ipywidgets==8.1.1
  - leafmap
  - ipysheet
  - solara
  - shapely
  - fiona
  - pip
  - pip:
    - geopandas

# Currently an issue with ipyleaflet/ipywidgets with the DrawControls, requiring fixed dependencies
# See : https://github.com/jupyter-widgets/ipyleaflet/issues/1119